GET http://localhost:8080/movies

###

GET http://localhost:8080/actors

###

GET http://localhost:8080/movieShows

###

POST http://localhost:8080/movies
Content-Type: application/json

{
    "title": "American Pie",
    "year": 1999,
    "rating": 7.0,
    "category": "Comedy",
    "director": "Paul Weitz",
    "description": "Four teenage boys enter a pact to lose their virginity by prom night.",
    "image": "https://m.media-amazon.com/images/M/MV5BMTg3ODY5ODI1NF5BMl5BanBnXkFtZTgwMTkxNTYxMTE@._V1_.jpg"
}
